### ISSUE TITLE
Discussion of Heberlein 2019 & Perry 2015

### ISSUE THREAD

**Issue by gabrielbodard** [SunoikisisDC/SunoikisisDC-2020-2021#11]
* Regine Heberlein (2019). "On the Flipside: Wikidata for Cultural Heritage Metadata through the Example of Numismatic Description." _IFLA WLIC 2019 - Athens, Greece - Libraries: dialogue for change in Session 206 - Art Libraries with Subject Analysis and Access._ Available: http://library.ifla.org/id/eprint/2492
* Sara Perry & Nicole Beale (2015). "The Social Web and Archaeology’s Restructuring: Impact, Exploitation, Disciplinary Change." _Open Archaeology_ 1.1. Available: https://doi.org/10.1515/opar-2015-0009

When reading these titles, be thinking about:
1. collaborative and crowdsourced scholarship
1. open licensed data and publications
1. using Social Web/Web 2.0 for research, not just dissemination
1. the power of using, querying, harvesting data from multiple sources

**Comment by nicolealexandra33** [comment]
**Sara Perry & Nicole Beale (2015). "The Social Web and Archaeology’s Restructuring: Impact, Exploitation, Disciplinary Change." Open Archaeology 1.1.**
Discussions about archaeology frequently intersect with those of heritage discourse, community, indigenous topics, socio-political movements, feminist and public archaeologies. For this reason, archaeologists often work in teams of people from different expertise backgrounds and methodologies.  However, despite the fact that archaeologists and heritage specialists have used the social web for already two decades, the engagement remains limited to a relatively small group of people, thus delaying archaeology’s progress in the field of digital humanities (in comparison with other humanities’ subjects). One reason for this is that in spite of the promoted attitude of intellectual democracy on open source platforms such as Wikipedia, people have nevertheless noted and critiqued that these platforms are not entirely open or without restrictions: ‘Various critiques of wiki technologies show that even they, with  their  “universal  collective  good”  as  supposedly  manifest  in  Wikipedia,  are  marked  by  interference,  control,  limited  engagement,  fragmentation,  non-neutrality,  and  aversion  to  responsibility.’ There are several other issues in social dynamics that have sprung forth from digital archaeology, such as the ‘corporate commodification of the university, and the destabilisation of the professoriate’. The other issue that has arisen is the amount of ‘volunteers’ who are interested in digital archaeology and digital heritage work who are willing to contribute significantly while receiving no pay, benefits, and working extreme hours as the online platform can be accessed anywhere; some have coined this phenomenon as ‘cognitive capitalism’ whereby one’s willingness to sacrifice time and effort is becoming more greatly valued. However, those who own and control such platforms can still make a profit off of such individuals’ efforts, while working under the guise of intellectual democracy and benevolence. The authors conclude: ‘We would suggest it also means conscientiously contesting investment in practices that compromise fair pay, fair working conditions, social equality, and basic human rights’, as well as they advocate for greater theorising of digital archaeology, so as to mitigate issues which may arise in the future.
Q1. As mentioned above, crowdsourced digital scholarship can often have an exploitative nature: ‘Crowdsourcing  applications  must  be  designed  carefully  to give  the  impression  that  participants  volunteer  and  are  not  working for free’ (emphasis ours), hinting at the exploitative politics that inevitably underlie such work.’ 
Q2. Open licensed data and publications allow people to ‘add to, edit, comment and remix content using a variety of interfaces, including those that are friendly to non-programmers and require only basic digital literacy’. However, as previously mentioned, some of these ‘open’ sources are not quite as open or unrestricted as they are described.
Q3.Social Web/Web 2.0 has also allowed for greater collaboration and openness surrounding issues of cultural heritage, and not simply keeping such authority within the hands of archaeologists and museum experts. These platforms also allow researchers to gain informers, as well as find collaborators who can add/edit their projects.
Q4. This has allowed for greater and more diverse engagement which in turn has also helped to ‘digitise’ archaeology further.

**Comment by LauraHead** [comment]
On the Flipside: Wikidata for Cultural Heritage Metadata through the Example of Numismatic Description, Regine Heberlein 2019

•	The article seeks to evaluate how the use of WikiData can be modelled through a project at Princeton University using the example of numismatics data 
•	Heberlein outlines advantages of Wikidata: cross-disciplinary potential, intuitive interface, quick response time, multi-lingual functions allowing it to become a ‘linking hub’ not just between languages but between disciplines, as has been picked up on by the community in proposing to be a movement-partner 
•	 The pitfalls of Wikidata are also outlined – problems of the ease of publishing baseless/inaccurate information and claims, leaving it up to the efficacy of crowdsourced editing and astuteness of community to police this
•	There is a current lack of consensus as to what model to implement that would best eliminate this obvious downside to allow Wikidata to be used more reliably as a community digital humanities resource
•	The experimental digital Numismatics project The Flipside consciously moved away from older document/narrative-based descriptive conventions, since Wikidata is not as well suited to discursive longer data 
•	The conceived plan for the project is to eventually use Wikidata for structured numismatic data, Wikipedia for text resources and Wikimedia Commons for images, but the author acknowledges that this way of working is highly counter-intuitive for a discipline used to strictly regulated content submission procedures and privacy protocols
•	The author proposes that the next phase of the project, involving setting up local Wikibase structures, will help counter some of these issues and demonstrate this model as a productive and useful one for resource description.

**Comment by despinaborcea** [comment]
With regards to the question of open licensed data and publications, as pointed in "On the Flipside: Wikidata for Cultural Heritage Metadata through the Example of Numismatic Description", one of the disadvantages of Wikidata is that, while it is easily accessible, it can also be easily edited by anyone without respecting the rigorous criteria established by the academic tradition in that field. Building on that point, potentially incorrect/unreferenced/incomplete information can be copied and used for other purposes, thus creating informative materials not only possibly wrong, but also not adhering to the academic consistency through which uniformity is achieved in the field. On the other hand, however, the accessibility of Wikidata grants non-specialist users easy access to the information, and allows specialist users to make justified corrections (which, again, can be further propagated due to the free use nature of open data materials).

**Comment by Kiamanx** [comment]
The idea of 'cognitive capitalism' explored in Parry & Beale is fascinating. Unfortunately it is ultimately true for Wikipedia, with people not receiving any accolades or even much recognition for their large contributions in keeping the main site as helpful for the average user as possible. Though the main philosophy of the site is free information curated for free so everyone can access it. It creates a dilemma of passion vs. profession.

**Comment by HLBallard44** [comment]
As someone who has a Bachelors's in archaeology and has worked both in the field and in an archaeology lab, I can attest to Sara Perry & Nicole Beale's article "The Social Web and Archaeology’s Restructuring: Impact, Exploitation, Disciplinary Change." While working in an archaeology lab, I cataloged records of archaeological digs. The majority of these archives are paper and housed in folders in a filing cabinet. Some of the reports are accessible on the computer, but they are located on the "Collections Management System" which can only be accessed by laboratory personnel. Therefore, the records are not available to the public.

I have also worked in the field on an urban archaeology project that was in the middle of downtown. The site was enclosed, but people could stop and ask questions. When talking to the public, we had to be careful about the information we provided and about the artifacts found. Since the dig was being funded by the city, an article was posted online about the project. The public could comment, and we had some positive comments, but we also had some backlash from the community. Therefore, the example in Perry and Beale's article: "Hill has published on her experiences of 'public ridicule' and 'being compromised professionally,' primarily at the hands of online comments on media outlets, for coverage of her contemporary archaeological fieldwork at a campsite in the Forest of Dean, UK," is something I can relate to and a critical issue in the archaeology industry.

**Comment by HLBallard44** [comment]
Another thing to add:
Most of the time, someone will be asked if they want to work on an archaeology dig through word of mouth. An archaeologist you had previously worked for may suggest you to another archaeologist who just started a dig. There are not a lot of archaeology jobs posted on Linked.in or indeed.

**Comment by nicolealexandra33** [comment]
Regarding the cognitive capitalism trend, I also wonder how it impacts all sectors, not just the digital humanities, especially now as almost everyone is working remotely. While it's great you save time/energy/fuel by not commuting, I think there will definitely be some managers/companies who will value workers based on how much overtime they are willing to put in without extra benefit especially as 'the work is accessible anywhere and all the time'
