### ISSUE TITLE
Help with Wikipedia/Wikimedia editing and research

### ISSUE THREAD

**Issue by gabrielbodard** [SunoikisisDC/SunoikisisDC-2020-2021#12]
If you have any problems with or questions about your use of Wikipedia or any other Wikimedia components, you may ask them here and we or your colleagues may have suggestions. Please keep an eye on this thread in case you can answer other people's questions too.

**Comment by chiaradimaio** [comment]
Dear all, 
I tried editing on Wikipedia, but I get this error message: 

Your username or IP address is blocked from doing this. You may still be able to do other things on this site, such as editing certain pages. You can view the full block details at account contributions. The IP address that you are currently using has been blocked because it is believed to be a web host provider.

It seems that this happens because I am using UCL's proxy. This is the only connection I can use at the moment, do you have any suggestions on how to fix the problem? Thank you.

**Comment by gabrielbodard** [comment]
Hi @chiaradimaio, were you able to edit before (to make the ten small edits we discussed)? Was that on a different network connection? (I've also passed this query to Richard, in case he has any suggestions.)

**Comment by RichardNevell** [comment]
@chiaradimaio  Would you be able to share the username you're using on Wikipedia? That way I should be able to check if you're affected by any blocks. It sounds like a network issue, in which case it should be possible to tweak some settings on your account.

**Comment by chiaradimaio** [comment]
Dear Gabriel and Richard, 
I tried accessing my account from a different network (in Italy) and this solved the issue: after that, I logged in again from the UK and it is now working. Sorry for the inconvenience and thank you for your help. I will let you know in case it should occur again, after I log out this session.

**Comment by RichardNevell** [comment]
Good to hear, I'm just glad it got solved!

**Comment by HLBallard44** [comment]
https://en.wikipedia.org/wiki/Kommos_(Crete)

**Comment by nicolealexandra33** [comment]
https://en.wikipedia.org/wiki/Greek_Magical_Papyri
And Despina worked more on: https://en.wikipedia.org/wiki/Ovid#Overview
