### ISSUE TITLE
Discussion of Drucker 2011 & Glinka 2017

### ISSUE THREAD

**Issue by gabrielbodard** [SunoikisisDC/SunoikisisDC-2020-2021#17]
* Johanna Drucker, “Humanities Approaches to Graphical Display”, *Digital Humanities Quarterly* 5.1, 2011, http://www.digitalhumanities.org/dhq/vol/5/1/000091/000091.html.
* Katrin Glinka, Pietsch C. and Dörk M., “Past Visions and Reconciling Views: Visualizing Time, Texture and Themes in Cultural Collections”, *Digital Humanities Quarterly* 11, 2017. Available: http://digitalhumanities.org/dhq/vol/11/2/000290/000290.html.

**Comment by LauraHead** [comment]
Glinka K., Pietsch C. and Dörk M., “Past Visions and Reconciling Views: Visualizing Time, Texture and Themes in Cultural Collections”, Digital Humanities Quarterly 11, 2017.

•	The authors present a case study involving the ‘close-viewing’ and ‘distant viewing’ of art heritage to demonstrate the potential impact of visualisation technology on cultural engagement projects
•	They outline prior work in related fields that this research seeks to build on, including literary projects, digital art history developments and methods of visualisation of cultural heritage collections that allow differently ‘distanced’ exploration
•	The authors point out that much of this progress in the field of material culture still comes from a stand-point of the ‘superiority’ of the physical object, which the authors themselves suggest can actually be problematised as limiting viewer engagement through the necessary and circumstantial restrictions inherent in displaying particularly fragile and ancient objects for example in museums
•	They argue that tool creation ought to be more in the hands of scholars as particularly certain models of visualisation, the example used is the linear timeline, can be limiting in presenting certain models of time where experts may wish to advance other temporal or thematic patterns but lack the input framework to do so 
•	Outlined is a growing interest in moving away from ‘overview’- centric models of visualisation to more blended approach that allows for this closer reading, offering both quantitative and qualitative insight 
•	The case study used is a collection of 1492 drawings by King Frederick William IV of Prussia, aiming to create a resource that worked off user feedback to make sense temporally and thematically of the content, but also allowed for close detail-reading, yielding a ‘zoomable’ visualisation tool utilising key words
•	Evaluation of the tool suggests this model was useful both as a research tool and as ‘cultural recreation’ that seeks to bridge a ‘quantitative-qualitative divide’ in humanities research

**Comment by annaszajbely** [comment]
Johanna Drucker, “Humanities Approaches to Graphical Display”, Digital Humanities Quarterly 5.1, 2011

Johanna Drucker's aim is to encourage humanists to  rethink graphical displays of data. IN her conclusion she claims herself that the essay is a “polemical call to humanists to think differently about the graphical expressions in use in digital environments. A fundamental prejudice, I suggest, is introduced by conceiving of data within any humanistic interpretative frame on a conventional, uncritical, statistical basis”. Drucker discusses the nature the nature of “data” and tries to define it as people inside and outside of humanities understand it. She says that data should become capta, meaning that it should be actively interpreted, rather than to stay purely data, which only accepted, as facts without any consideration of interpretation.

It is important to keep in mind that the data given to us is already interpreted in a visual display, but it is a question how much of this interpretation had been lost. What se means that there are two different task that has to be executed: first the representation of ambiguity and uncertainty and second the representation of observer-codependence interpretations. She claims that these two are different, and must be treated differently. In chapter Data as Capta we can see an example of a international binary gender population graph. Her argument here is that the “constructed interpretation of the phenomenal world” data is capta. She argues that graphical interpretations should be used to express individual reading of data, so that it is emphasises that the interpretation is never complete.
 
Time and Space
Since humanists deal with multiply data that drive from various times, and spaces: time for them is “discontinuous, multi-directional, and variable”, while space is “also always constructed according to a specific agenda and situated experience”. The scholars who deal with data analysis within the field of humanities need a model of temporality in order to present and interpret the documents from various times that they are dealing with and also a way to show the importance of the relationship between time and space and the variety of space when they are dealing with a certain document of artefact.

**Comment by nicolealexandra33** [comment]
Not to be cliche again, but I think these discussions are particularly relevant when discussing the Cult of Mithras, as there is so much material attributed to the Cult, yet a lot of the examples which at a micro level can be disputed, or have a lot of 'marginal' examples and variations (ex.: provincial versus 'Roman'). Obviously if one attempted to represent these examples visually, the graphs (or other representations) would vary significantly depending on how this material was categorised

**Comment by HLBallard44** [comment]
While reading Glinka, Pietsch, and Dörk's article "Past Visions and Reconciling Views: Visualizing Time, Texture, and Themes in Cultural Collections," I compared my experience of viewing museum artifacts digitally and uploading artifact information onto a museum's collections management system. Recently, I viewed an artifact on the National Geographic website that was three-dimensional. Meaning I could click and drag or touch and rotate the artifact to see it from different angles. You could also click on specific areas/designs on the artifact, and a text box of information would appear. It also included the zoomable feature like in the article. Being able to rotate an artifact 360 degrees provides an opportunity for close-up visualization that would not be possible in a museum. However, I also believe that seeing an artifact in real life is an extraordinary experience.
Especially at this time when the pandemic has forced everyone to an online platform, do you believe that a platform like the one mentioned in the article would be a good source for research for art historians, scholars, archaeologists, etc.?

**Comment by annaszajbely** [comment]
Well, I think you are right, like watching an artefact on any online platform is never going to be the same, even reading in an online platform is not as "good" as reading an actual book in my opinion. But I think if you are a researcher, then it is not enough anyway if you just go to the museum and look at it like visitors do, then you have to apply for the artefact's 'study leave', if it is exhibited, if not, then all good. Which you can do during covid. In the meantime, certainly you can study it through the online platform, but certainly not every detail could be shown in a digital platform (manuscripts, artefacts etc) So I think the digital platform is a good help, but no serious researcher would write an article on an object that they have never seen before in real life. The problem with the pandemic is obviously the visitors, I think online museum tours are great, but as you said, not the same. Auction galleries suffer a lot with the auction being online, great, but the exhibition before the auction must be held, (even though they have these amazing digital platforms, and as you said rotating Picasso and all one can imagine) because nobody wants to buy a painting let us say for a million pounds that they have never seen in real life. Because (especially) a painting looks strikingly different on an online platform. So I think it only works for research, and for the beginning of the research. Visitors and customers are never going to be fully satisfied with only an online platform only. I think the online versions are a good complement, maybe people would not feel the need to take photos as much, if these digital representations were more popular.

**Comment by despinaborcea** [comment]
I certainly agree with Anna's point about art - I think in-person visualisation of the art is crucial to the understanding of it/decision to purchase it etc. I also think it's true that visitors will not agree with the online version only. However, to build up on that in a different direction, there is a conception that could be detrimental to the preservation of the art/archaeological/other forms of material culture objects etc, which is that 'digital' equals 'less' and is therefore not as an enriching an experience as in-person viewing. In this sense, digital-only is occasionally necessary, if one bears in mind, for example, the number of scholars (alone!) that want/need to look at, say, Magna Carta, and that is even excluding external viewers, like tourists. If everyone got to shuffle through the book, it would probably be irreversibly damaged in a very short span of time!

**Comment by Kiamanx** [comment]
I'm super biased so I'm going to expand on Nicole's point about Mithras. There really have not been many accurate visualisations of the Mithraic sites because for some reason the people quantifying the info leave out some of the more minor sites while arbitrarily incorporating others. It seems the key of the visualisations really depends on who is doing them.

**Comment by nicolealexandra33** [comment]
@Kiamanx Agreed! I think the best way to do it would be if some persistent person basically made a map with multiple layers to represent the multiple criteria of limiting 'Mithraic finds'. Based on the geographic spread, there may be a possibility to prove which of these criteria is most likely. However, you obviously need to be critical the entire way, and I can imagine that the whole process will be very long and arduous

**Comment by gabrielbodard** [comment]
@nicolealexandra33 @Kiamanx: I'm interested in talking more about Mithras some time, but for the purposes of the current discussion the important thing to take away is that (1) yes the effectiveness and accuracy of a visualisation is 99% dependent on the quality of the data you feed into it (data preparation is > 60% of any digital research); and (2) every visualisation is the result of the methods, decisions and assumptions that go into designing it, and is **at best** either a communication of a certain interpretation of the data or inspiration for a new way of looking at it. There's no such thing as one, correct visualisation of any dataset or topic.
