### ISSUE TITLE
Discussion of Nyhan  2012 & Rosselli 2016

### ISSUE THREAD

**Issue by gabrielbodard** [SunoikisisDC/SunoikisisDC-2020-2021#3]
* Nyhan, J. (2012). “Text encoding and scholarly digital editions”. In _Digital Humanities in Practice_, edited by C. Warwick, M. Terras, J. Nyhan. London: Facet Publishing. Pre-proof available: <https://www.researchgate.net/profile/Julianne_Nyhan/publication/284178309_Text_encoding_and_digital_scholarly_editions/links/564e2b2f08aefe619b0fad83/Text-encoding-and-digital-scholarly-editions.pdf>
* Roberto Rosselli Del Turco (2016). "The Battle We Forgot to Fight: Should We Make a Case for Digital Editions?" In _Digital Scholarly Editing: Theories and Practices_, M. J. Driscoll and E. Pierazzo (eds.). Pp. 219-238. Available <https://www.openbookpublishers.com/htmlreader/978-1-78374-238-7/ch12.xhtml#_idTextAnchor029>

Some questions to get us started:
1. Who are the authors and what relationship do they have to the material they're discussing? Does this change how we read their arguments, understand their agendas, etc.?
1. How have digital methods changed the way we edit, publish, read critical editions of ancient texts?
1. Do you think digital classical editions have any unique needs and requirements over other disciplines? (NB: Neither Nyhan nor Rosselli are classicists.)
1. Do you think digital editions are recognised and accepted as a legitimate output in classics? Will that change? Should it?

**Comment by LauraHead** [comment]
The Battle We Forgot to Fight: Should We Make a Case for Digital Editions?
Roberto Rosselli Del Turco
•	The ‘Golden age’ of digital pioneering was decade from 1990s-2004, spawning many digital editions, yet actual scholarly uptake of these was low, despite their alleged superiority, due to scepticism of medium. The article seeks to outline how far digital editions have ‘succeeded’ in the decade since. 
•	Despite a marked increase of enthusiasm for digital journal articles for research and e-books for teaching, there remains a reluctance to foresee relinquishment of hard copies in library collections. Digital resources are still underused despite proliferation of such projects and the wealth of features and material they can offer.  
•	Rosselli de Turco outlines what he feels is the root of this low uptake. Firstly software - lack of standardized or easy to use production method compared to print publishing, and need for more resources to benefit from all the features offered by an SDE. Lack of reliability of digital referencing due to software lifespan and issues over role of publisher. 
•	Perception problems – a lack of awareness of benefits of SDEs among scholars, leading to lack of credit for those who work on their production and shortfall in taking advantage of full benefits of digital editions even by those who produce them.
•	Solutions to this impasse are suggested as improvement in usability, focusing on user-friendly production software with minimal necessary training; providing a sustainable and reliable host for SDEs and interface improvement taking possible cues from the success of e-readers. Rosselli del Turco feels building up institutional resources of SDEs will contribute to their accelerating popularity over coming years if these factors are properly addressed.

**Comment by nicolealexandra33** [comment]
(Q2 and a bit Q4) Rosselli explains in-depth the pros and cons, as well as the fundamental differences between printed editions and digital editions. Because of these differences, he argues that these versions can be and even should be used for to achieve different goals and tasks. One example that Nyhan describes is the ability to cross-reference through large quantities of texts using digitised editions. On the other hand, Rosselli explains that there is not yet one type of standardised software best suited to digitise any type of edition, thus making it more challenging for authors to have to learn various types of software and then needing to decide which is best suited for digitising their text.

(Q4) Regarding editions, Rosselli explains that less tech-savvy colleagues have a hard time distinguishing a ‘digitised edition’ from a ‘digital edition’. This misinterpretation often makes it very hard to convince such colleagues the benefits of creating digital editions.

**Comment by chiaradimaio** [comment]
Text encoding and digital scholarly editions, Julianne Nyhan, UCL, 201
This article by Julianne Nyhan is focused on Text Encoding, which is the act of applying metadata (information about information) to a text, in order to make it machine readable. This is regarded as a core research area in the field of digital humanities (and beyond, since Text Encoding has had an influence on the development of XML languages). 
The author provides a definition of a digital humanities text: ‘a digital text that supports research and\or is the result of research’ and she lists the main features a digital scholarly text should have:
•	Provide bibliographical data and essential information
•	Describe editorial decisions and workflow (for instance, the normalisation of spelling)
•	Use open source technologies and software: the editions will be not become obsolete due to platform updates
•	Declare editorial theory on which the edition is based (the so-called modelling)
•	Be able to interact with other digital texts.
This is followed by an historical excursus about the origins of TEI: its principles were declared during a conference held in 1987 in Poughkeepsie (and got the name of Poughkeepsie Principles; they are not prescriptive, but give advice and examples on how to encode a textual feature). The fifth and latest edition of ‘Design Principles for text encoding guidelines’, (known as P5 Guidelines, 2007) enables researchers to insert tags into a text in order to make it machine readable: this process is called markup. The term is thought to come from publishing, where a writer could mark corrections or instructions. There are three different types of markup:
•	Presentational: aims to specify some aspects of its appearance. 
•	Procedural: acts to implement presentational instructions
•	Descriptive: this one has shown many advantages, because it separates form and content of a document, giving information on the second one only (i.e., it described what a unit is: noun, glyph etc.)
Today, one of the most common ways of implementing markup is using XML (extensible mark-up language), which is a fixed corpus of tags (504 at the moment) that can be applied to a document to reflect three types of information: structural, content descriptive and visual. The main disadvantage is that this distinction is hierarchical and does not allow the overlap of information.
There is still much research to do on this topic; researchers have criticized some aspects of TEI, such as the complexity of the guidelines and the limitation of its abstract model.

**Comment by HLBallard44** [comment]
Roberto Rosselli Del Turco is the author of chapter 12 "The Battle We Forgot to Fight: Should We Make a Case for Digital Editions?" in _Digital Scholarly Editing Theories and Practices._ He is a professor at the Universita Degli Studi di Torino and teaches a Digital Philology course. While Julianne Nyhan is an Associate Professor of Digital Information Studies at University College London and the Programme Director for MA/MSc in Digital Humanities. Professor Roberto Rosselli Del Turco has an understanding of what is required to make a literary text into a digital edition, and the pros and cons that are associated with it. His focus is strictly on philology and scholarly digital editions. Julianne Nyhan, I presume, has a broader sense of digital humanities. She does not focus specifically on literary texts, but on digital humanities as a whole.
I believe both are good sources because they provide two different perspectives. One focuses on literary texts and making them into digital editions while the other focuses on the technical side of the Text Encoding Initiative: its advantages and disadvantages, and examples of projects being done in digital humanities.
