### ISSUE TITLE
Discussion of Almas/Beaulieu 2016 & Simon/Vitale 2019

### ISSUE THREAD

**Issue by gabrielbodard** [SunoikisisDC/SunoikisisDC-2020-2021#9]
* Almas B. & Beaulieu M. 2016. "The Perseids Platform: Scholarship for all!" In Romanello M. & Bodard G, _Digital Classics Outside the Echo-Chamber_. Ubiquity Press. Available: https://doi.org/10.5334/bat.j
* Rainer Simon, Valeria Vitale, Rebecca Kahn, Elton Barker & Leif Isaksen. 2019. “Revisiting Linking Early Geospatial Documents with Recogito.” _e-Perimetron_ 14-3, 150–163. Available: http://www.e-perimetron.org/Vol_14_3/Simon_et_al.pdf

Questions to think about include:
1. Provenance of papers and background of authors
1. Collaboration and openness—how annotations are useful for others after you publish them
1. Digital vs. traditional/print/analogue—can annotation expand or enhance traditional commentaries, apparatus, or similar?

**Comment by nicolealexandra33** [comment]
**Rainer Simon, Valeria Vitale, Rebecca Kahn, Elton Barker & Leif Isaksen. 2019. “Revisiting Linking Early Geospatial Documents with Recogito.” e-Perimetron 14-3, 150–163.**
‘Recogito is an open source tool for semantic annotation’ which allows for a great number of applications and techniques for collaboration and is maintained by the Pelagios Network, a ‘non-profit association advocating and enabling the production and use of linked open geo-data in the humanities and cultural heritage’. Recogito was first introduced in 2015 where it was only used internally on a project called Pelagios, but received a great deal of attention subsequently. This encouraged the development of the newer version of Recogito which included a friendlier user interface suited for both non-technical and experienced users; and greater support for general annotation (namely marking up of people, places, things, etc.) and TEI texts. Besides annotations, another useful function for which it allows is the digitisation and markup of maps. Once they are digitised, it also allows for the map data to be converted fairly easily, in order to be exported via different software. Much like other hosting programs, there is also a tab for downloads as well as documents and controls for collaboration levels. However, the authors acknowledge that Recogito can be used in a number of unique, new ways, and as such, the platform is constantly evolving to include new tools. Some of the best known projects which have been made possible with Recogito include ‘The Lazarus Project,’ ‘Digging into Early Colonial Mexico’, ‘Kima’, and ‘Pelagios al Sur’. It has also proven to be a very useful teaching tool, especially with undergraduates who are learning new concepts and being introduced to ancient sources, as Recogito can display such information in a more engaging way.
Q1. Rainer Simon is a Research Software Engineer with a focus on semantic technologies. Valeria Vitale’s research involves the development of a documentation standard for scholarly 3D visualisation. Rebecca Kahn focuses on the digitisation of museums and archives. Elton Barker has a variety of cross-disciplinary interests, including one of his projects that investigates how Herodotus creates space in his Histories. Leif Eriksen is a Digital Humanities Theme Lead for the Institute of Data Science and AI (IDSAI) who focuses on spatial and temporal representations in the humanities. Overall, all of the authors are involved with digital humanities research and projects which accounts for their encouragement and promotion of the use of software like Recogito.
Q2 & Q3. Digital annotations (as opposed to traditional print annotations) allow for greater collaboration, a full record and list of users who have contributed to the annotations, as well as the ability to have ‘micro-discussions’ about the content. This allows for collaboration and editing of annotations at any point in the publication process of a project, work, etc. 
Q3. Because there is still some difficulty with digitising hand-drawn maps, there is a possibility of losing some data which can only be traced in print form.

**Comment by HLBallard44** [comment]
Almas B. & Beaulieu M. "The Perseids Platform: Scholarship for all!" 
The authors discuss the benefits of using crowdsourcing as a way to produce large quantities of digital documents, particularly the Perseids platform which allows users of any skill level to attempt annotation and editing work. 
Their main target audience for who would benefit from using Perseids is not Classicists but students and members of the public. 
The authors divide the article into three sections: 
1. The audience of classics scholarship
- Classics encompasses many disciplines that involve a large body of people who are not established scholars or specialists and it is important to integrate them without compromising quality or accessibility 
- The Perseus Digital Library aims to make records of humanities intellectually accessible to every person, so they designed the Perseids collaborative editing platform to allow a broad audience to contribute to Perseus and to fully access data at any time.
2. Pedagogy and Scholarship
- The Perseids platform allows students create editorial projects, annotations, and morpho-syntactic analyses and trains them as researchers.
- Living publications, such as Arethusa, lets members of the community distribute their work and allows suggestions, feedback, and ideas on their publications.
- Utilising collaborative teaching methods, such as work done on Perseids, enables students to "produce concrete works and serves to support further scholarship and learning activities."
3. What is Scholarship?
- Scholarship is defined as a "the way in which knowledge is produced: the methods, discipline, and achievements"
- Perseids: helps analyze and understand languages
- tools in the Alpheios project offers insights into texts and translation choices
- the Imgspect tool links transcripts to images of the document
- the Canonical Text Services Unique Resource Name translates canonical citations into "technology independent and machine actionable form"
Perseids allows individuals of different expertise to engage in the practice and publication of scholarly data. This encourages students to become passionate about their research because it provides them with an opportunity to publish works that are a part of larger projects in the Perseus Digital Library.

**Comment by chiaradimaio** [comment]
It can be interesting to notice that both articles draw attention on how these informatic tools could be useful for both specialists and students. Collaboration could be a new, key concept in teaching Classics, creating a stimulating environment in which the student feels encouraged to try and progress autonomously, after having been guided through the process first. 

Q3. Text annotation is probably the first expression of any philological activity. I think new tools could allow scholars to  better visualize what their work aims at and what is the state of the art. However, as with any change in estabilished practice, it will take long before online encoding becomes more immediate than the 'traditional' way of writing commentaries and apparati. I would compare this change to the passage from the papyrus roll to the codex: shifting to a completely digital environment will also require a change in the traditional visualization we have of the book page and of how we would put philological and critical notes on that.

**Comment by despinaborcea** [comment]
1.	Background
Bridget Almas is a software developer and project manager for Perseus Digital Library. While she has a background in modern foreign languages, she is not a Classicist _per se_. Marie-Claire Beaulieu is an Associate Professor in Classical Studies at the Tufts University. She has a strong interest in both Ancient Greek Religion, as well as Digital Humanities. As such, she co-directs the Perseid Project.

2.	 Collaboration and Openness 
With regards to collaboration, I think the answer depends on the content of the annotations. While some scholars/students could make valuable observations on texts, it could also be the exact opposite. 

3.  Digital vs. traditional 
One of the points Almas and Beaulieu make in the article is referring to the advantages of crowdsourcing, one of which being the accessibility of materials, no longer bound to geographical parameters. I believe that, building up on the accessibility point, annotations from scholars with different backgrounds can potentially enhance commentaries as well as an apparatus criticus.

**Comment by nicolealexandra33** [comment]
Just a general comment after having done the Recogito activity-- I appreciate the user-friendliness of the software as intended by the authors/creators

**Comment by LauraHead** [comment]
Regarding Q2, I think the Simon/Vitale/Kahn/Barker/Isaksen article really adds to the ongoing thread through this programme dealing with the idea of resistance to digital humanities techniques within the discipline. The idea that Recogito, as Chiara has mentioned, is intended particularly to be accessible as a method of exposure to and training in digital projects for students as well as established researchers, helps to assure the progress of digital humanities in the future by nurturing generations of classical scholars who may be more familiar and comfortable with such methods from the beginning of their careers, allowing for greater scope for inter-generational and cross-disciplinary study in the future. I agree with Nicole in that using the Recogito tool for the project this week has really highlighted what the authors were trying to afford someone like myself who is newer to such tools by creating a very accessible software.

**Comment by HLBallard44** [comment]
I concur with everything that Laura has stated. Training the next generation with Recogito (and other opensource platforms) will allow them to be more open with digital humanities than the current generation. Even if a student will not proceed with a career specifically in Digital Classics/Humanities, having the basic discipline that Recogito provides will allow them to further their research or vocation.

**Comment by gabrielbodard** [comment]
Gratified by all the love for Recogito (which is a tool I also find very valuable) but I want to unpick a little the question of convincing classicists/philologists with its user-friendliness. What exactly are classicists being convinced to do or adopt by using an easy interface like this? What traditional/classical research agenda is annotation in Recogito contributing to? Is there a danger that being __too__ easy to use makes it look like a toy? Have you seen this used in any of your ancient history/archaeology courses? What would you use it for, in your research?
